on:
  issues:
    types: [ labeled ]
  pull_request:
    types: [ labeled ]

jobs:
  add-wontfix-umbrella-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if 'wontfix' already exists on the issue/pr
        uses: actions/github-script@v6
        id: check-wontfix
        with:
          # probably simpler than this, but fuck it
          script: |
            const labelToCheck = 'wontfix';

            // Get the labels on the issue or PR
            const { data: labels } = await github.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            // Check if the label is present
            const labelExists = labels.some(label => label.name === labelToCheck);

            core.setOutput('wontfix-exists', labelExists);

      - name: Add wontfix label to Issue (if applicable)
        if: ${{ github.event_name == 'issue' }}
        run: |
          echo ${{ steps.check-wontfix.outputs.wontfix-exists }}

      - name: Add wontfix label to Pull Request (if applicable)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo ${{ steps.check-wontfix.outputs.wontfix-exists }}
